# Generated by Django 2.0.8 on 2018-12-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181210_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
