# Generated by Django 2.0.8 on 2018-11-26 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_name', models.CharField(max_length=50)),
                ('race_time', models.CharField(max_length=50)),
                ('race_day', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Runner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horse_name', models.CharField(max_length=50)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runners', to='home.Race')),
            ],
        ),
    ]
