# Generated by Django 2.0.8 on 2018-11-27 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_selection'),
    ]

    operations = [
        migrations.AddField(
            model_name='selection',
            name='runner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='home.Runner'),
        ),
        migrations.AlterField(
            model_name='selection',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='home.Race'),
        ),
    ]
