# Generated by Django 2.0.8 on 2018-11-27 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20181127_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selection',
            name='race',
        ),
        migrations.AlterField(
            model_name='selection',
            name='runner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='home.Runner'),
        ),
    ]
