# Generated by Django 2.0.8 on 2018-11-28 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20181127_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='runner',
        ),
        migrations.AddField(
            model_name='runner',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Result',
        ),
    ]
