# Generated by Django 2.0.8 on 2018-11-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20181128_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='runner',
            name='odds',
            field=models.IntegerField(default=0),
        ),
    ]
