# Generated by Django 2.0.8 on 2018-11-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_runner_odds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runner',
            name='odds',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
