# Generated by Django 2.0.8 on 2018-11-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20181128_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runner',
            name='odds',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
