# Generated by Django 2.0.8 on 2018-11-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20181130_1220'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Day',
        ),
        migrations.AlterField(
            model_name='race',
            name='day',
            field=models.IntegerField(default=0),
        ),
    ]
