# Generated by Django 2.0.8 on 2018-12-03 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='selection',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
