# Generated by Django 2.0.8 on 2018-12-04 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_selection_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.Day'),
        ),
    ]
