# Generated by Django 2.0.8 on 2018-12-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20181204_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='runner',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
