# Generated by Django 2.0.8 on 2018-12-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20181210_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runner',
            name='odds',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
