# Generated by Django 2.0.8 on 2019-02-20 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20181210_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='runner',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='runner',
            name='position',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
