# Generated by Django 2.0.8 on 2019-02-20 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20190220_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='runner',
            name='non_runner',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='runner',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
